routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'ThreadsController@index');
Route::get('/threads/search', 'SearchController@show');
Route::get('/threads/{channel}/{thread}', 'ThreadsController@show');
Route::delete('/threads/{channel}/{thread}', 'ThreadsController@destroy');
Route::post('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store');
Route::delete('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy');

Route::get('/channels/create', 'ChannelsController@create')->middleware('email-must-be-confirmed');
Route::post('/channels/store', 'ChannelsController@store')->middleware('email-must-be-confirmed');

Route::get('/threads/create', 'ThreadsController@create');
Route::get('/threads/{channel}', 'ThreadsController@index');

Route::post('/threads', 'ThreadsController@store')->middleware('email-must-be-confirmed');
Route::post('/replies/{reply}/favorites', 'FavoritesController@store');
Route::delete('/replies/{reply}/favorites', 'FavoritesController@destroy');
Route::post('/replies/{reply}/best', 'FavoritesController@best');

Route::get('/threads/{channel}/{thread}/replies', 'RepliesController@index');
Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store');

Route::delete('/replies/{reply}', 'RepliesController@destroy');
Route::patch('/replies/{reply}', 'RepliesController@update');

Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');

Route::get('/profiles/{user}/notifications', 'UserNotificationsController@index');
Route::delete('/profiles/{user}/notifications/{notification}', 'UserNotificationsController@destroy');

Route::get('/api/users','Api\UserController@index');
Route::post('/api/users/{user}/avatar','Api\UserAvatarController@store')->middleware('auth');
Route::get('/register/confirm','Api\RegisterConfirmationController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Thread.php
<?php

namespace App;

use App\Events\ThreadHasNewReply;
use App\Filters\ThreadFilters;
use App\Notifications\ThreadWasUpdated;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Thread extends Model
{
    //

    use RecordsActivity;//Searchable;


    // from Searchable trait
    public function toSearchableArray()
    {
        return $this->toArray() + ['thread_path'=> $this->path()];
    }
    protected $guarded = [];
    protected $with = ['creator', 'channel'];
    protected $appends = ['IsSubscribed'];

    public function scopeFilter($query, ThreadFilters $filters){
//        dd($query->toSql());
        return $filters->apply($query);
    }

    public function path(){
        return "/threads/{$this->channel->slug}/{$this->id}";
    }
    public function subscribe($user_id = null){
        return $this->subscriptions()->create(['user_id' => $user_id ?: auth()->id()]);
    }
    public function unsubscribe($user_id = null){
        return $this->subscriptions()->where('user_id', $user_id ?: auth()->id())->delete();
    }
    public function replies(){
        return $this->hasMany(Reply::class);
//        return $this->hasMany(Reply::class)->withCount('favorites')->with('owner');
    }
    public function subscriptions(){
        return $this->hasMany(ThreadSubscription::class);
    }
    public function creator(){
       return $this->belongsTo(User::class,'user_id');
    }

    public function addReply($reply){
        $reply = $this->replies()->create($reply);

        event(new ThreadHasNewReply($reply));

        return $reply;
    }

    public function channel(){
        return $this->belongsTo(Channel::class);
    }
    protected static function boot()
    {
        parent::boot();
         // thread replies count for all the routs
        static::addGlobalScope('replyCount',function ($builder){
            $builder->withCount('replies');
        });
        static::deleting(function ($thread){
            // in order to trigger RecordsActivity trait static::deleting() method
            // to delete activity for each reply. Simple $thread->replies()->delete() doesn't work here
            $thread->replies->each->delete();
        });
    }
    public function getIsSubscribedattribute(){
        return $this->subscriptions()->where('user_id',auth()->id())->exists();
    }
    public function hasUpdatesFor($user){
        $key = $user->visitedThreadCacheKey($this);
        return $this->updated_at > cache($key);
    }
    public function visits(){
        return new Visits($this);
    }
    public function markBestReply(Reply $reply){
        $this->update(['best_reply_id'=>$reply->id]);
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Channel;
use App\Inspections\Spam;
use App\Rules\Recaptcha;
use App\Rules\SpamFree;
use App\Thread;
use App\Filters\ThreadFilters;
use App\Trending;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ThreadsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }

    public function index(Channel $channel, ThreadFilters $filters, Trending $trending)
    {
        // TODO when a thread gets deleted, update $trending
        $threads = $this->getThreads($channel, $filters);
        $trending = $trending->get();
        return view('threads.index',compact('threads','trending'));
    }

    protected function getThreads(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);
//        dd($threads->toSql());
        if ($channel->exists) {
            $threads->where('channel_id', $channel->id);
//           $threads = Thread::where('channel_id',$channel->id)->get();
        }
        return $threads->paginate(5);
    }

    public function create()
    {
        return view('threads.create');
    }

    public function store(Request $request, Spam $spam)
    {
        request()->validate([
           'title'=> ['required',new SpamFree],
           'body'=> ['required',new SpamFree],
            'channel_id'=> 'required|exists:channels,id',
            'g-recaptcha-response'=> [new Recaptcha()]
        ]);

        $thread = Thread::create([
            'title'=> $request->title,
            'body'=> request('body'),
            'user_id'=> auth()->id(),
            'channel_id'=> $request->channel_id
        ]);
        return redirect($thread->path())->with('flash','Yor thread has been published');
    }

    public function show($channelID,Thread $thread, Trending $trending)
    {
        if (auth()->check()) {
            auth()->user()->read($thread);
        }
        $trending->push($thread);

        $thread->visits()->record();

        return view('threads.show',[
            'thread' => $thread,
            'replies' => $thread->replies()->paginate(15)
        ]);

    }
    public function edit(Thread $thread)
    {
        //
    }

    public function update(Request $request, Thread $thread)
    {
        //
    }

    public function destroy($channel, Thread $thread)
    {
        //
        $this->authorize('update',$thread);

        $thread->delete();
        return redirect('/threads');
    }

}

resources/views/threads/_list.blade.php
@forelse($threads as  $thread)
    <div class="card" style="margin: 20px;">
        <div class="card-body">
            <article>
                <div class="level">
                    {{--@if (auth()->check() && $thread->hasUpdatesFor(auth()->user()))--}}
                        {{--<h4><strong><a href="{{$thread->path()}}">{{$thread->title}}</a></strong></h4>--}}
                    {{--@else--}}
                        <h4><a href="{{$thread->path()}}">{{$thread->title}}</a></h4>
                    {{--@endif--}}
                    <div class="body flex">
                        <p>{!! $thread->body !!}</p>
                        <strong style="white-space: nowrap; align-self: flex-end">{{ $thread->replies_count }} {{ str_plural('reply',$thread->replies_count) }} </strong>
                    </div>
                </div>
            </article>
            <hr>
        </div>
        <div class="card-footer">
            {{ $thread->visits()->count() }} Visits
        </div>
    </div>
@empty
    <p>No results</p>
@endforelse

resources/views/threads/create.blade.php
@extends('layouts.app')
@section('header')
    <script src='https://www.google.com/recaptcha/api.js'></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Create a New Thread</div>

                    <div class="panel-body">
                        <form method="POST" action="/threads">
                        {{ csrf_field() }}

                            <div class="form-group">
                                @if (count($errors))
                                    <ol class="alert alert-danger">
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ol>
                                @endif
                                <label for="channel_id">Choose a Channel:</label>
                                <select name="channel_id" id="channel_id" class="form-control" required>
                                    <option value="">Choose One...</option>

                                    @foreach ($channels as $channel)
                                        <option value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : '' }}>
                                            {{ $channel->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="title">Title:</label>
                                <input type="text" class="form-control" value="{{ old('title')}}" id="title" name="title" required>
                            </div>

                            <div class="form-group">
                                <label for="body">Body:</label>
                                <wysiwyg name="body"></wysiwyg>
                                {{--<textarea class="form-control" value="{{ old('body')}}" id="body" rows="6" name="body" required></textarea>--}}
                            </div>
                            <div class="form-group">
                                <div class="g-recaptcha" data-sitekey="6LeewGIUAAAAAPgaTyag-TlgArxPG4u0vW14-5hF"></div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Publish</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
             @include('threads._list')
                <div class="row justify-content-center">
                        {{ $threads->render() }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        Trending threads
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            @foreach($trending as $trend)
                                <a href="{{ url($trend->path) }}">{{ $trend->title }}</a>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/reply.blade.php
<reply :attributes="{{ $reply }}" inline-template v-cloak>
<div id="{{ 'reply-' . $reply->id }}" class="card" style="margin: 20px">
    <div class="card-header">
        <a href="{{ route('profile',$reply->owner->name) }}">{{$reply->owner->name}}</a> said
        {{$reply->created_at->diffForHumans()}}
    </div>

    <div class="card-body">
        <div v-if="editing">
            <div class="form-group">
                <div class="form-group">
                    <textarea class="form-control" v-model="body">{{$reply->body}}</textarea>
                </div>
                <button class="btn btn-xs btn-primary" @click="update">Update</button>
                <button class="btn btn-xs" @click="editing = false">Cancel</button>
            </div>
        </div>
        <div v-else v-text="body">
            {{$reply->body}}
        </div>

        <favorite :reply="{{ $reply }}"></favorite>

        @can('update',$reply)
            <div class="flex" >
                <button class="btn btn-danger btn-small" @click="destroy">Delete</button>
                <button class="btn btn-xs btn-default" @click="editing = true" style="">Edit</button>
            </div>
        @endcan
    </div>
</div>
</reply>

resources/views/threads/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
                <ais-index class="row col-md-12"
                        app-id="{{ config('scout.algolia.id') }}"
                        api-key="{{ config('scout.algolia.key') }}"
                        index-name="threads"
                       :query-parameters="{
                       }"

                >
                    <div class="col-md-8">
                        <ais-results inline-template>
                            {{--<template slot-scope="{ result }">--}}
                            <ol>
                                <li v-for="result in results" :key="result.id">
                                    <a :href="result.thread_path">
                                        <ais-highlight :result="result" attribute-name="title"></ais-highlight>
                                    </a>
                                </li>
                            </ol>
                            {{--</template>--}}
                        </ais-results>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <ais-search-box>
                                <ais-input placeholder="Find a thread" :autofocus="true" class="form-control"></ais-input>
                            </ais-search-box>
                        </div>
                        <div class="form-group">
                            <ais-refinement-list attribute-name="channel.name"></ais-refinement-list>
                        </div>
                    </div>
             </ais-index>
    </div>
@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')
@section('header')
    <link rel="stylesheet" href="{{ asset('css/vendor/jquery.atwho.css') }}">
@endsection
@section('content')
    <thread-view :initial_rep_count="{{ $thread->replies_count }}" inline-template>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="card" style="margin-bottom: 20px;">
                        <div class="card-header">
                            <a href="{{ route('profile',$thread->creator->name) }}">{{ $thread->creator->name }}</a> posted:
                            <a href="{{ $thread->path() }}">{{$thread->title}}</a>
                            @can('update',$thread)
                                <form class="pull-right" action="{{ $thread->path() }}" method="POST">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-link">Delete thread</button>
                                </form>
                            @endcan
                        </div>
                        <div class="card-body">
                            {!! $thread->body !!}
                        </div>
                    </div>
                    <replies  @removed="RepliesCount--"
                              @added="RepliesCount++"
                    >
                    </replies>

                </div>
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <p>
                                This thread was published {{ $thread->created_at->diffForHumans() }} by
                                <a href="#">{{ $thread->creator->name }}</a>, and currently
                                has <span v-text="RepliesCount"></span> {{ str_plural('comment', $thread->replies_count) }}
                            </p>
                            <p>
                                <subscribe-button :active="{{ json_encode($thread->IsSubscribed)}}"></subscribe-button>
                                <button class="btn btn-outline-primary" @click="locked = true">Lock</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </thread-view>
@endsection